version: '3.8'
services:
  payment-subscription:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-subscription
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres
    links:
      - postgres
    env_file:
      - .env
    networks:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    expose:
      - "5432"
    networks:
      - postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-prisma-docker-db
  data:
    external: true
networks:
  postgres:
    driver: bridge